baseURL = "https://herolfg.com/"
languageCode = "en-us"
title = "HeroLFG"
theme = "hugo-coder-modified"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "herolfg"

[params]
    owner = "Gavin Palmer"
    author = "HeroLFG LLC"
    info = "Telework Software Services"
    description = "Teaching and learning the best ways to work remotely."
    keywords = "minerval,minerva,arts,minerval arts,space elevator,telework,education,process improvement"
    avatarurl = "images/profile_pic.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Always Learning"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]
    colorscheme = "dark"
    hideCredits = true
    hideCopyright = false
    since = 2014

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/GavinPalmer1984/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/herolfg/"
[[params.social]]
    name = "Stackoverflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 3
    url = "https://stackoverflow.com/users/1686280/gavin-palmer"
[[params.social]]
    name = "Hackerrank"
    icon = "fab fa-hackerrank fa-2x"
    weight = 4
    url = "https://www.hackerrank.com/gavinpalmer1984"

# Menu links
[[menu.main]]
    name = "Posts"
    weight = 1
    url = "posts/"
[[menu.main]]
    name = "Contact"
    weight = 2
    url  = "contact/"
